name: Android Pull Request Workflow

on:
  pull_request:
    branches:
      [develop, master]

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Kotlin Linter
        run: sh ./gradlew ktlint

      - name: Run Android Linter
        run: sh ./gradlew lint

      - name: Run Tests
        run: sh ./gradlew test
